# Generated by Django 4.1.4 on 2025-02-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
    ]
