# Generated by Django 4.1.4 on 2025-02-10 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
