# Generated by Django 4.1.4 on 2025-02-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_reportfile_delete_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='route',
            field=models.CharField(default='Reports/', max_length=255),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(upload_to=models.CharField(default='Reports/', max_length=255)),
        ),
    ]
