# Generated by Django 4.1.4 on 2025-02-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_reportfile_route_alter_reportfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='route',
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(upload_to='Reports/'),
        ),
    ]
