# Generated by Django 4.1.4 on 2025-02-10 23:53

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_reportfile_route_alter_reportfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(upload_to=system.models.report_upload_path),
        ),
    ]
